services:
  db:
    image: postgres:15-alpine
    container_name: mkp_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: mkp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mkp_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    container_name: mkp_mongo_express
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:123@mongodb:27017/?authSource=admin"
      ME_CONFIG_BASICAUTH_USERNAME: admin_ui
      ME_CONFIG_BASICAUTH_PASSWORD: admin_ui_password
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    restart: unless-stopped
  # ... (outros serviços)
  # --- NOSSA APLICAÇÃO GO ---
  app:
    container_name: mkp_go_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mongodb
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      # AJUSTE FINAL AQUI
      MONGO_URI: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/?authSource=admin"
      JWT_SECRET: ${JWT_SECRET}
    restart: on-failure
# ... (resto do arquivo)
volumes:
  postgres_data:
  mongo_data: